### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by coleHafner** [tajuma/supl#1]
I get an error when trying to compile from source. It seems like the compiler is not generating the `ENUMERATED.o` file in the `asn-supl` directory. Here are the steps I took:

**Steps to reproduce**
```
./configure --enable-debug --enable-supl-debug
make
```

**Expected**
`supl-client` compiles

**Actual**
Error:
```
make[3]: *** No rule to make target 'ENUMERATED.o', needed by 'libasnsupl.a'.  Stop.
```

**Environment**
box: Ubuntu 16.04.6 LTS
asn1c: v0.9.27 (also tried on v0.9.28 and latest master)

I know I can configure with the `--precompiled-asn1` option, but I'm trying to debug my SUPL connection and I believe that the precompiled doesn't include debugging? The reason being is a simple test like `supl-client -t 3 <supl url>` produces `SUPL protocol error -1`. This could happen for several reasons, which is why I would like the debugging statements.

**Comment by tajuma** [comment]
It looks like (for some reason) ENUMERATED is not needed for asn.1. I simply commented out that in Makefiles in src/asn-rrlp and src/asn-supl.

There were also missing OpenSSL cyrpto library and some compiler warnings. All these should be fixed in commit fcb73db. Unfortunately I am not able to test this anymore but at least it compiles now.

**Comment by coleHafner** [comment]
Hi @tajuma  Thanks for the quick reply. I cannot get it to compile any more. Now I run into the following error: 

```
./libsupl.so: undefined reference to `asn_DEF_ENUMERATED'
```

My steps are:
```
./configure --precompiled-asn1
make
```

My config file looks like this:
```
# Generated by ./configure script - Wed Oct 16 10:35:00 PDT 2019
# Modifications to this file are lost if ./configure is ran again.

CONF_VERSION = 1.0.5
CONF_CFLAGS = -Wall -O2
CONF_ASN_CFLAGS =
CONF_PREFIX = /usr/local
CONF_PRECOMPILED_ASN = yes
CONF_SUPL_DEBUG =
CONF_ASN1_SKELETONS =
```

What environment are you able to compile on? So far I've tried `Ubuntu 16` and, most recently, `Raspbian GNU/Linux 9.4 (stretch)`.

**Comment by tajuma** [comment]
Ok, precompiled asn1 files still require building ENUMERATED.c/h while compiling with a recent asn1 compiler from the source it is not generated anymore. 

Commit 2f81488 should now work with and without precompiled files. This is just a quick hackish fix, proper fix would require repackaging precompiled files with a current asn1 compiler, I think.

**Comment by tajuma** [comment]
Closing as resolved.
