### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by utya** [tajuma/supl#4]
Good afternoon. I managed to build everything from source, but every time I try to start the proxy, I get an error
Error: Valid server certificate not found in srv-cert.pem

OpenSSl veriosn 1.1.1f
ubuntu 22.04

**Comment by tajuma** [comment]
Just checking... did you build and run supl-cert as described in README?

**Comment by utya** [comment]
Problem in supl-cert. It generate not valid certs. With letsencrypt it works

**Comment by tajuma** [comment]
supl-cert uses SHA-1 in signing the cert, some providers (e.g. Google) may reject the cert because of it. One thing to test is to change it SHA2 and see if it is good to go again.
