### ISSUE TITLE
always SUPL protocol error -2

### ISSUE THREAD

**Issue by vsitdikov** [tajuma/supl#6]
Seems asn1 parser fails on ulp start but I can not understand what error is . Could you please assist?

Host info:

user@host:~/work/temp/supl/src$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
user@host:~/work/temp/supl/src$ uname -a
Linux vs-lenovo-t15 5.19.0-38-generic #39~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Mar 17 21:16:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

Problem log:

$ LD_LIBRARY_PATH=$PWD ./supl-client -t 3
uper_encode_to_buffer 
Encoding "ULP-PDU" using UNALIGNED PER (per_encoder.c:40)
Encoding ULP-PDU as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
ext_after = -1, ec = 4, eb = -1 (constr_SEQUENCE.c:1362)
About to encode INTEGER (constr_SEQUENCE.c:1373)
Encoding ULP-PDU->length (constr_SEQUENCE.c:1395)
Encoding NativeInteger INTEGER 0 (UPER) (NativeInteger.c:282)
Value 0 (00/1) lb 0 ub 65535 fix (INTEGER.c:712)
Encoding integer with range 16 bits (INTEGER.c:730)
[PER put 16 bits 0 to 0x7ffee6430668+0 bits] (per_support.c:277)
[PER out 16 0/0 (t=0,o=16) 90&0=0] (per_support.c:315)
[PER out 0/0 => 00 buf+0] (per_support.c:344)
Freeing INTEGER as a primitive type (asn_codecs_prim.c:125)
About to encode Version (constr_SEQUENCE.c:1373)
Encoding ULP-PDU->version (constr_SEQUENCE.c:1395)
Encoding Version as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
ext_after = -1, ec = 3, eb = -1 (constr_SEQUENCE.c:1362)
About to encode INTEGER (constr_SEQUENCE.c:1373)
Encoding Version->maj (constr_SEQUENCE.c:1395)
Encoding NativeInteger INTEGER 1 (UPER) (NativeInteger.c:282)
Value 1 (01/1) lb 0 ub 255 fix (INTEGER.c:712)
Encoding integer with range 8 bits (INTEGER.c:730)
[PER put 8 bits 1 to 0x7ffee6430668+16 bits] (per_support.c:277)
[PER out 8 1/1 (t=0,o=8) 5c&0=0] (per_support.c:315)
[PER out 1/1 => 01 buf+2] (per_support.c:344)
Freeing INTEGER as a primitive type (asn_codecs_prim.c:125)
About to encode INTEGER (constr_SEQUENCE.c:1373)
Encoding Version->min (constr_SEQUENCE.c:1395)
Encoding NativeInteger INTEGER 0 (UPER) (NativeInteger.c:282)
Value 0 (00/1) lb 0 ub 255 fix (INTEGER.c:712)
Encoding integer with range 8 bits (INTEGER.c:730)
[PER put 8 bits 0 to 0x7ffee643066a+8 bits] (per_support.c:277)
[PER out 8 0/0 (t=0,o=8) dd&0=0] (per_support.c:315)
[PER out 0/0 => 00 buf+3] (per_support.c:344)
Freeing INTEGER as a primitive type (asn_codecs_prim.c:125)
About to encode INTEGER (constr_SEQUENCE.c:1373)
Encoding Version->servind (constr_SEQUENCE.c:1395)
Encoding NativeInteger INTEGER 0 (UPER) (NativeInteger.c:282)
Value 0 (00/1) lb 0 ub 255 fix (INTEGER.c:712)
Encoding integer with range 8 bits (INTEGER.c:730)
[PER put 8 bits 0 to 0x7ffee643066b+8 bits] (per_support.c:277)
[PER out 8 0/0 (t=0,o=8) ef&0=0] (per_support.c:315)
[PER out 0/0 => 00 buf+4] (per_support.c:344)
Freeing INTEGER as a primitive type (asn_codecs_prim.c:125)
About to encode SessionID (constr_SEQUENCE.c:1373)
Encoding ULP-PDU->sessionID (constr_SEQUENCE.c:1395)
Encoding SessionID as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
Element ptr wtv SessionID->setSessionID is present (constr_SEQUENCE.c:1351)
[PER put 1 bits 1 to 0x7ffee643066c+8 bits] (per_support.c:277)
[PER out 1 1/1 (t=0,o=1) 7f&0=0] (per_support.c:315)
[PER out 128/80 => 80 buf+5] (per_support.c:344)
Element ptr wtv SessionID->slpSessionID is absent (constr_SEQUENCE.c:1351)
[PER put 1 bits 0 to 0x7ffee643066d+1 bits] (per_support.c:277)
[PER out 1 0/0 (t=1,o=2) 80&80=80] (per_support.c:315)
[PER out 0/0 => 80 buf+5] (per_support.c:344)
ext_after = -1, ec = 2, eb = -1 (constr_SEQUENCE.c:1362)
About to encode SetSessionID (constr_SEQUENCE.c:1373)
Encoding SessionID->setSessionID (constr_SEQUENCE.c:1395)
Encoding SetSessionID as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
ext_after = -1, ec = 2, eb = -1 (constr_SEQUENCE.c:1362)
About to encode INTEGER (constr_SEQUENCE.c:1373)
Encoding SetSessionID->sessionId (constr_SEQUENCE.c:1395)
Encoding NativeInteger INTEGER 1 (UPER) (NativeInteger.c:282)
Value 1 (01/1) lb 0 ub 65535 fix (INTEGER.c:712)
Encoding integer with range 16 bits (INTEGER.c:730)
[PER put 16 bits 1 to 0x7ffee643066d+2 bits] (per_support.c:277)
[PER out 16 1/1 (t=2,o=18) 80&c0=80] (per_support.c:315)
[PER out 64/40 => 80 buf+5] (per_support.c:344)
Freeing INTEGER as a primitive type (asn_codecs_prim.c:125)
About to encode SETId (constr_SEQUENCE.c:1373)
Encoding SetSessionID->setId (constr_SEQUENCE.c:1395)
Encoding SETId as CHOICE (constr_CHOICE.c:919)
Encoding SETId CHOICE element 3 (constr_CHOICE.c:941)
[PER put 1 bits 0 to 0x7ffee643066d+18 bits] (per_support.c:277)
[PER out 1 0/0 (t=2,o=3) 40&c0=40] (per_support.c:315)
[PER out 0/0 => 40 buf+7] (per_support.c:344)
[PER put 3 bits 3 to 0x7ffee643066f+3 bits] (per_support.c:277)
[PER out 3 3/3 (t=3,o=6) 40&e0=40] (per_support.c:315)
[PER out 12/c => 4c buf+7] (per_support.c:344)
Encoding OCTET STRING into 8 units of 8 bits (8..8, effective 0) (OCTET_STRING.c:1568)
Encoding 8 bytes (0), length in 0 bits (OCTET_STRING.c:1601)
Squeezing 8 characters into (0..0):8 (1 bpc) (OCTET_STRING.c:1264)
[PER put 24 bits ffff91 to 0x7ffee643066f+6 bits] (per_support.c:277)
[PER out 24 16777105/ffff91 (t=6,o=30) 4c&fc=4c] (per_support.c:315)
[PER out 67108420/3fffe44 => 4f buf+7] (per_support.c:344)
[PER put 24 bits 944845 to 0x7ffee643066f+30 bits] (per_support.c:277)
[PER out 24 9717829/944845 (t=6,o=30) 44&fc=44] (per_support.c:315)
[PER out 38871316/2512114 => 46 buf+10] (per_support.c:344)
[PER put 16 bits 8398 to 0x7ffee6430672+30 bits] (per_support.c:277)
[PER out 16 33688/8398 (t=6,o=22) 14&fc=14] (per_support.c:315)
[PER out 134752/20e60 => 16 buf+13] (per_support.c:344)
About to encode SlpSessionID (constr_SEQUENCE.c:1373)
Element slpSessionID 1 not present (constr_SEQUENCE.c:1379)
About to encode UlpMessage (constr_SEQUENCE.c:1373)
Encoding ULP-PDU->message (constr_SEQUENCE.c:1395)
Encoding UlpMessage as CHOICE (constr_CHOICE.c:919)
Encoding UlpMessage CHOICE element 1 (constr_CHOICE.c:941)
[PER put 1 bits 0 to 0x7ffee6430675+22 bits] (per_support.c:277)
[PER out 1 0/0 (t=6,o=7) 60&fc=60] (per_support.c:315)
[PER out 0/0 => 60 buf+15] (per_support.c:344)
[PER put 3 bits 1 to 0x7ffee6430677+7 bits] (per_support.c:277)
[PER out 3 1/1 (t=7,o=10) 60&fe=60] (per_support.c:315)
[PER out 64/40 => 60 buf+15] (per_support.c:344)
Encoding SUPLSTART as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
[PER put 1 bits 0 to 0x7ffee6430677+10 bits] (per_support.c:277)
[PER out 1 0/0 (t=2,o=3) 40&c0=40] (per_support.c:315)
[PER out 0/0 => 40 buf+16] (per_support.c:344)
Element ptr wtv SUPLSTART->qoP is absent (constr_SEQUENCE.c:1351)
[PER put 1 bits 0 to 0x7ffee6430678+3 bits] (per_support.c:277)
[PER out 1 0/0 (t=3,o=4) 40&e0=40] (per_support.c:315)
[PER out 0/0 => 40 buf+16] (per_support.c:344)
ext_after = 2, ec = 3, eb = 4 (constr_SEQUENCE.c:1362)
About to encode SETCapabilities (constr_SEQUENCE.c:1373)
Encoding SUPLSTART->sETCapabilities (constr_SEQUENCE.c:1395)
Encoding SETCapabilities as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
[PER put 1 bits 0 to 0x7ffee6430678+4 bits] (per_support.c:277)
[PER out 1 0/0 (t=4,o=5) 40&f0=40] (per_support.c:315)
[PER out 0/0 => 40 buf+16] (per_support.c:344)
ext_after = 2, ec = 3, eb = 4 (constr_SEQUENCE.c:1362)
About to encode PosTechnology (constr_SEQUENCE.c:1373)
Encoding SETCapabilities->posTechnology (constr_SEQUENCE.c:1395)
Encoding PosTechnology as SEQUENCE (UPER) (constr_SEQUENCE.c:1312)
[PER put 1 bits 0 to 0x7ffee6430678+5 bits] (per_support.c:277)
[PER out 1 0/0 (t=5,o=6) 40&f8=40] (per_support.c:315)
[PER out 0/0 => 40 buf+16] (per_support.c:344)
ext_after = 6, ec = 7, eb = 8 (constr_SEQUENCE.c:1362)
About to encode BOOLEAN (constr_SEQUENCE.c:1373)
Encoding PosTechnology->agpsSETassisted (constr_SEQUENCE.c:1395)
[PER put 1 bits 0 to 0x7ffee6430678+6 bits] (per_support.c:277)
[PER out 1 0/0 (t=6,o=7) 40&fc=40] (per_support.c:315)
[PER out 0/0 => 40 buf+16] (per_support.c:344)
uper_encode_internal -1
Failed to encode element ULP-PDU (per_encoder.c:153)
Freeing ULP-PDU as SEQUENCE (constr_SEQUENCE.c:958)
Freeing INTEGER as INTEGER (1, 0x5568a213f400, Native) (NativeInteger.c:325)
Freeing Version as SEQUENCE (constr_SEQUENCE.c:958)
Freeing INTEGER as INTEGER (1, 0x5568a213f408, Native) (NativeInteger.c:325)
Freeing INTEGER as INTEGER (1, 0x5568a213f410, Native) (NativeInteger.c:325)
Freeing INTEGER as INTEGER (1, 0x5568a213f418, Native) (NativeInteger.c:325)
Freeing SessionID as SEQUENCE (constr_SEQUENCE.c:958)
Freeing SetSessionID as SEQUENCE (constr_SEQUENCE.c:958)
Freeing INTEGER as INTEGER (1, 0x5568a213f600, Native) (NativeInteger.c:325)
Freeing SETId as CHOICE (constr_CHOICE.c:1038)
Freeing OCTET STRING as OCTET STRING (OCTET_STRING.c:1725)
Freeing UlpMessage as CHOICE (constr_CHOICE.c:1038)
Freeing SUPLSTART as SEQUENCE (constr_SEQUENCE.c:958)
Freeing SETCapabilities as SEQUENCE (constr_SEQUENCE.c:958)
Freeing PosTechnology as SEQUENCE (constr_SEQUENCE.c:958)
Freeing PrefMethod as a primitive type (asn_codecs_prim.c:125)
Freeing PosProtocol as SEQUENCE (constr_SEQUENCE.c:958)
Freeing LocationId as SEQUENCE (constr_SEQUENCE.c:958)
Freeing CellInfo as CHOICE (constr_CHOICE.c:1038)
Freeing WcdmaCellInformation as SEQUENCE (constr_SEQUENCE.c:958)
Freeing INTEGER as INTEGER (1, 0x5568a213f4f8, Native) (NativeInteger.c:325)
Freeing INTEGER as INTEGER (1, 0x5568a213f500, Native) (NativeInteger.c:325)
Freeing INTEGER as INTEGER (1, 0x5568a213f508, Native) (NativeInteger.c:325)
Freeing Status as a primitive type (asn_codecs_prim.c:125)
SUPL protocol error -2

**Comment by Raviu56** [comment]
Any solution to this issue?
@tajuma @buzztiaan

**Comment by tajuma** [comment]
Sorry for a very late response... 

there seems to be some issues with the precompiled asn1c files and used asn1c compiler version to generate them. The latest Ubuntu asn1c 0.9.28 seems to work with a small patch to supl.c. 

I updated the precompiled asn1c files and supl.c patch. 

This still depends on outdated openssl-1.1 which must be installed, see at the bottom my quick'n'dirty way to build this without actually installing openssl-1.1.

Then

```
% LD_LIBRARY_PATH=./root/usr/lib/x86_64-linux-gnu:. ./supl-client -t 3
T 270 3052637 1718135393 13916
U -2 -3 18 99 11 137 7 18
I 21 3 -2 62 10 -3 -4
E 16
e 1 17213 889331659 -1592911311 -210052627 652497351 704767725 -23354 -475 114877810 240 3465 8104 320 -123 15 15300 6 15300 560784 -53 0 1 0 63 -42 31
e 2 12709 56271696 -1592945311 1152987570 661092515 -804225507 -23487 414 137356769 1721 3274 8613 2020 -78 -102 15300 36 15300 -900925 62 0 1 0 0 -38 31
e 3 11580 1932309413 -1592936135 1928935841 673249425 749993021 -22272 -325 47989871 -1382 1911 10224 -1524 14 -93 15300 78 15300 878031 158 0 1 0 0 3 31
e 4 11894 -324448406 -1592921995 -1629133209 659695454 -2017593315 -22050 -277 24375876 -2088 4878 6612 -2249 32 12 15300 13 15300 818405 72 0 1 0 0 -10 31
e 5 12925 153868373 -1592983769 1893711888 664313488 862571914 -23496 -252 50730839 -797 1779 10278 -1079 -26 9 15300 32 15300 -377905 -12 0 1 0 0 -23 31
e 6 11140 -1443580457 -1592976254 1220445989 676394814 -474932960 -21986 534 25422228 2138 3089 9180 2436 -36 16 15300 88 15300 480932 -185 0 1 0 0 8 31
e 7 12778 -2043950698 -1592978971 -936740135 649307903 -1447043133 -21520 972 159733738 226 4635 6528 361 51 -80 15300 101 15300 -205858 96 0 1 0 0 -24 31
e 8 12919 -96685782 -1592972979 470953213 651534655 250270487 -22916 -478 81315643 1074 4507 6853 1134 48 42 15300 259 15300 483192 161 0 1 0 0 10 31
e 9 12383 229559876 -1592967221 -1669898538 655351914 1349110708 -22372 -234 23567129 -2109 4764 6657 -2351 -19 -9 15300 54 15300 496104 128 0 1 0 0 2 31
e 10 11887 1256241124 -1592950644 1927181735 673015812 -1621876967 -22615 -177 80302593 -1027 2017 10365 -1137 -125 14 15300 69 15300 -87647 -71 0 1 0 0 5 31
e 11 12693 -570530781 -1592931866 1242823543 660363353 -1770558751 -22812 568 11555574 2041 3029 8779 2325 9 9 15300 431 15300 -1467452 -72 0 1 0 0 -19 31
e 12 12609 1749695170 -1592978831 -174074665 657962710 992862430 -21863 -333 75022760 311 3462 8127 357 53 6 15300 21 15300 -1102230 -28 0 1 0 0 -27 31
e 13 11838 -282267016 -1592965148 -1556340473 664100154 632204023 -22341 -196 69924736 -2174 4987 6474 -2501 -7 59 15299 6 15299 1411391 23 0 1 0 0 -24 31
e 14 13914 1726317454 -1592947003 -204600243 646547212 -1978310373 -22910 -338 39333404 319 3476 7823 296 -51 -6 15300 586 15300 908544 80 0 1 0 0 -17 31
e 15 14304 -745795408 -1592962156 -1757579393 639609529 898824836 -23756 -540 134787463 -2361 4117 6930 -2808 -36 211 15300 83 15300 363086 37 0 1 0 0 -22 31
e 16 12949 528144855 -1593012498 -161875862 657608412 572144593 -23011 -751 118715659 265 3617 8080 243 -93 47 15300 36 15300 -573326 92 0 1 0 0 -22 31
```

#### How to build with non-system openssl-1.1

```
git clone https://github.com/tajuma/supl.git
cd supl

wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.1.1f-1ubuntu2_amd64.deb
wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
dpkg-deb -x libssl1.1_1.1.0g-2ubuntu4_amd64.deb root
dpkg-deb -x libssl-dev_1.1.1f-1ubuntu2_amd64.deb root

OPENSSL_CFLAGS="-I/tmp/supl/root/usr/include -I/tmp/supl/root/usr/include/x86_64-linux-gnu" OPENSSL_LDFLAGS="-L/tmp/supl/root/usr/lib/x86_64-linux-gnu -lssl -lcrypto" make -j20

LD_LIBRARY_PATH=/tmp/supl/root/usr/lib/x86_64-linux-gnu:/tmp/supl/src ./src/supl-client -t 3
```

**Comment by Raviu56** [comment]
@tajuma 
Thanks it works now, on OpenSuSE, just `sudo zypper install asn1c openssl-1_1 libopenssl1_1` then
```
./configure && make -j $(nproc)
```
And it works fines.

I find that it does not retrieve any almanac despite `-a`
Also, it only retrieves ephemeris of GPS constellation, not Glonass, Galileo, Beidou, is this a limitation in your code or from server side? As I found on other - currently broken - implementations that it should support other constellations too?

**Comment by tajuma** [comment]
Looks like google returns almanac info at random, see e.g. ([https://devzone.nordicsemi.com/f/nordic-q-a/108486/supl-google-com-not-returning-almanac-data-anymore](https://devzone.nordicsemi.com/f/nordic-q-a/108486/supl-google-com-not-returning-almanac-data-anymore)). At least the almanac request flag is set on supl request.

Support for other GNSSes than GPS might require an upgrade to SUPLv2 protocol. Currently this only supports SUPLv1 and it would take some effort to update. I have not had any use for this software for many years now... but happy to take merge requests ;-)

**Comment by Raviu56** [comment]
I'm not that programmer, but here is supl2 implementation -no merged for some reason - that can help/inspire someone https://github.com/gnss-sdr/gnss-sdr/tree/supl2

**Comment by tajuma** [comment]
Thanks for the info.

Closing this issue for now.
